-- =========================================================================
-- LOCAL SUPABASE DATABASE SCHEMA MIGRATION
-- =========================================================================
-- Location: supabase/migrations/0001_schema.sql
-- 
-- This migration builds the public-safe database schemas, tables, views,
-- RLS policies, and grants for the local Supabase environment.
-- =========================================================================

-- Create logical namespaces (schemas)
CREATE SCHEMA IF NOT EXISTS "core";
CREATE SCHEMA IF NOT EXISTS "kitchen";
CREATE SCHEMA IF NOT EXISTS "books";
CREATE SCHEMA IF NOT EXISTS "med";
CREATE SCHEMA IF NOT EXISTS "api";

-- =========================================================================
-- 1. CORE SCHEMA (User contexts, sessions, and FSM states)
-- =========================================================================

-- core.persons
-- Logical identity within the family space.
CREATE TABLE "core"."persons" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "person_key" text UNIQUE, -- e.g., 'member_a', 'member_b'
    "display_name" text NOT NULL,
    "first_name" text,
    "last_name" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- core.app_users
-- Telegram client binding mapping to a family member identity.
CREATE TABLE "core"."app_users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "telegram_user_id" bigint UNIQUE, -- Synthetic Telegram User ID for tests
    "auth_user_id" uuid UNIQUE REFERENCES auth.users("id") ON DELETE SET NULL, -- Mapping to Supabase Auth User
    "person_id" bigint REFERENCES "core"."persons"("id") ON DELETE CASCADE,
    "display_name" text NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- core.runtime_app_sessions
-- FSM session logs tracking bot-user conversation context.
CREATE TABLE "core"."runtime_app_sessions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "telegram_user_id" bigint REFERENCES "core"."app_users"("telegram_user_id") ON DELETE CASCADE,
    "current_state" text NOT NULL,
    "state_data" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "started_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- core.telegram_chat_audit
-- Audit trail tracking incoming events and processed response logs (safe placeholders).
CREATE TABLE "core"."telegram_chat_audit" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "telegram_user_id" bigint,
    "direction" text NOT NULL, -- 'inbound' | 'outbound'
    "message_type" text NOT NULL, -- 'text' | 'voice' | 'photo'
    "intent_detected" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);


-- =========================================================================
-- 2. KITCHEN SCHEMA (Recipes, dishes, ratings, and attachments)
-- =========================================================================

-- kitchen.dishes
-- Represents recipes and cooking records saved by users.
CREATE TABLE "kitchen"."dishes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" bigint REFERENCES "core"."app_users"("id") ON DELETE CASCADE,
    "title" text NOT NULL,
    "recipe" text, -- Full instructions and details
    "photo_main" text, -- Path to main image in storage (public-safe URI sketch)
    "photo_main_thumb" text,
    "photo_main_hash" text,
    "photos" text[] DEFAULT '{}'::text[],
    "rating" smallint CONSTRAINT "dishes_rating_check" CHECK ((("rating" >= 1) AND ("rating" <= 10))),
    "tags" text[] DEFAULT '{}'::text[],
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);


-- =========================================================================
-- 3. BOOKS SCHEMA (Library management and reading progress)
-- =========================================================================

-- books.reading_status
-- Reading session status tracking.
CREATE TYPE "books"."reading_status" AS ENUM (
    'to_read',
    'reading',
    'finished',
    'abandoned'
);

-- books.authors
-- Literary authors metadata.
CREATE TABLE "books"."authors" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text UNIQUE NOT NULL,
    "bio" text,
    "notes" text,
    "personal_rating" smallint CONSTRAINT "authors_personal_rating_check" CHECK ((("personal_rating" >= 1) AND ("personal_rating" <= 10))),
    "created_at" timestamp with time zone DEFAULT now()
);

-- books.books
-- Library entries collected by the family.
CREATE TABLE "books"."books" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" text NOT NULL,
    "author_id" bigint REFERENCES "books"."authors"("id") ON DELETE SET NULL,
    "isbn_10" text,
    "isbn_13" text,
    "description" text,
    "cover_url" text,
    "page_count" integer,
    "published_year" integer,
    "language" text DEFAULT 'ru'::text,
    "axes" jsonb DEFAULT '{}'::jsonb, -- custom multi-dimensional ratings
    "impression" text,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now()
);

-- books.notes
-- Interactive notes / highlights extracted from book pages.
CREATE TABLE "books"."notes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "book_id" bigint REFERENCES "books"."books"("id") ON DELETE CASCADE,
    "content" text NOT NULL,
    "source" text DEFAULT 'manual'::text, -- 'manual' | 'agent_extraction'
    "conversation_id" text,
    "created_at" timestamp with time zone DEFAULT now()
);

-- books.reading_sessions
-- Reading progress metrics.
CREATE TABLE "books"."reading_sessions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "book_id" bigint REFERENCES "books"."books"("id") ON DELETE CASCADE,
    "status" books.reading_status DEFAULT 'to_read'::books.reading_status NOT NULL,
    "started_at" date,
    "finished_at" date,
    "progress_percent" smallint DEFAULT 0 CONSTRAINT "reading_sessions_progress_check" CHECK ((("progress_percent" >= 0) AND ("progress_percent" <= 100))),
    "rating" smallint CONSTRAINT "reading_sessions_rating_check" CHECK ((("rating" >= 1) AND ("rating" <= 10))),
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now()
);


-- =========================================================================
-- 4. MED SCHEMA (High-granularity health tracker)
-- =========================================================================

-- med.medical_entries
-- Multi-metric journal logs tracking blood pressure, glucose, and notes.
CREATE TABLE "med"."medical_entries" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_by_user_id" bigint REFERENCES "core"."app_users"("id") ON DELETE CASCADE,
    "subject_person_id" bigint REFERENCES "core"."persons"("id") ON DELETE CASCADE,
    "metric_type" text NOT NULL CONSTRAINT "medical_entries_metric_type_check" CHECK (("metric_type" = ANY (ARRAY['blood_pressure'::text, 'glucose'::text, 'note'::text]))),
    "systolic" integer,  -- blood pressure: systolic
    "diastolic" integer, -- blood pressure: diastolic
    "pulse" integer,     -- heart rate pulse
    "glucose_value" double precision, -- glucose level (e.g. 5.6)
    "glucose_unit" text DEFAULT 'mmol/L'::text,
    "glucose_context" text, -- e.g., 'fasting', 'after_meal'
    "note_text" text,       -- unstructured contextual details
    "raw_text" text,        -- original message transcribed by the agent
    "measured_at" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "status" text DEFAULT 'confirmed'::text NOT NULL CONSTRAINT "medical_entries_status_check" CHECK (("status" = ANY (ARRAY['confirmed'::text, 'needs_review'::text])))
);


-- =========================================================================
-- 5. API SCHEMA (Tokens and external API audit scopes)
-- =========================================================================

-- api.token_scopes
-- Synthetic auth schema demonstrating token-to-scopes binding for external clients.
CREATE TABLE "api"."token_scopes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "app_name" text NOT NULL,
    "scopes" text[] NOT NULL, -- e.g., '{"recipes:read", "health:write"}'
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- api.request_logs
-- Synthetic API request tracking logs.
CREATE TABLE "api"."request_logs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "token_id" bigint REFERENCES "api"."token_scopes"("id") ON DELETE SET NULL,
    "endpoint" text NOT NULL,
    "method" text NOT NULL,
    "status_code" integer NOT NULL,
    "response_time_ms" integer,
    "ip_address" text DEFAULT '127.0.0.1'::text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);


-- =========================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =========================================================================

ALTER TABLE "core"."app_users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "kitchen"."dishes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "books"."books" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "med"."medical_entries" ENABLE ROW LEVEL SECURITY;

-- 1. App Users Policy: Allow users to view their own profile mapping
CREATE POLICY select_own_app_user ON "core"."app_users"
    FOR SELECT TO authenticated
    USING (auth_user_id = auth.uid());

-- 2. Dishes Policies
CREATE POLICY select_all_dishes ON "kitchen"."dishes"
    FOR SELECT TO authenticated
    USING (true);

CREATE POLICY modify_own_dishes ON "kitchen"."dishes"
    FOR ALL TO authenticated
    USING (user_id = (
        SELECT id FROM core.app_users WHERE auth_user_id = auth.uid()
    ));

-- 3. Books Policies
CREATE POLICY access_all_books ON "books"."books"
    FOR ALL TO authenticated
    USING (true);

-- 4. Medical Entries Policies: Restricted to active users registered in app_users
CREATE POLICY access_family_medical_entries ON "med"."medical_entries"
    FOR ALL TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM core.app_users 
            WHERE app_users.auth_user_id = auth.uid() 
              AND app_users.is_active = true
        )
    );


-- =========================================================================
-- API GRANTS FOR SUPABASE ROLES
-- =========================================================================

-- Grant Schema Usages
GRANT USAGE ON SCHEMA "core" TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA "kitchen" TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA "books" TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA "med" TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA "api" TO anon, authenticated, service_role;

-- Grant Service Role Access (Bypasses RLS by default, but good practice to grant)
GRANT ALL ON ALL TABLES IN SCHEMA "core" TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA "kitchen" TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA "books" TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA "med" TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA "api" TO service_role;

-- Grant Authenticated Role Access (Controlled by RLS policies)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "core" TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "kitchen" TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "books" TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "med" TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "api" TO authenticated;

-- Grant Anonymous Role Access (Controlled by RLS if enabled)
GRANT SELECT ON ALL TABLES IN SCHEMA "core" TO anon;
GRANT SELECT ON ALL TABLES IN SCHEMA "kitchen" TO anon;
GRANT SELECT ON ALL TABLES IN SCHEMA "books" TO anon;
GRANT SELECT ON ALL TABLES IN SCHEMA "med" TO anon;
GRANT SELECT ON ALL TABLES IN SCHEMA "api" TO anon;

-- Grant Sequence Usage for Auto-increment Identity Columns
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "core" TO authenticated, anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "kitchen" TO authenticated, anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "books" TO authenticated, anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "med" TO authenticated, anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "api" TO authenticated, anon;
